seed_everything: 42
trainer:
  accelerator: tpu
  devices: 8
  precision: bf16-mixed
  logger:
    class_path: WandbLogger
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: ModelCheckpoint
      init_args:
        monitor: validation/loss