seed_everything: 42
trainer:
  logger:
    class_path: WandbLogger
    init_args:
      project: khs-ket5
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: ModelCheckpoint
      init_args:
        monitor: validation/loss