trainer:
  accelerator: cpu
  fast_dev_run: true
  logger:
    init_args:
      offline: true
model:
  class_path: model.KeT5Small
  init_args:
    lr: 1e-4
    num_warmup_epochs: 10
    tokenizer:
      class_path: tokenizer.KeT5Tokenizer
data:
  class_path: data.KHSDataModule
  init_args:
    batch_size: 2
    tokenizer:
      class_path: tokenizer.KeT5Tokenizer