trainer:
  accelerator: cpu
  logger:
    init_args:
      offline: True
experiment:
  task: khs
  model: keT5Small
  pad_to: 128
  batch_size: 2
  is_gpu: False
  hp:
    lr: 1e-4
    num_warmup_epochs: 10
